CONFIG_DYNAMIC_INTERRUPTS=y

# Tăng độ chính xác của các hàm delay/sleep (k_msleep, k_usleep)
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# Bật hỗ trợ tính toán số thực (Float) cho thuật toán PID/Kalman Filter
CONFIG_FPU=y

# Tăng kích thước bộ nhớ Stack mặc định cho luồng Main (tránh tràn RAM khi tính toán nhiều)
CONFIG_MAIN_STACK_SIZE=512

# K_WORK
CONFIG_SYSTEM_WORKQUEUE_PRIORITY=2

# Bật bộ xuất log Console của hệ thống
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Bật thư viện in chuỗi (printf,printk)
CONFIG_PRINTK=y
CONFIG_EVENTS=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="My Drone CDC"
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y

CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_MONITOR=y
